apiVersion: v1
kind: Service
metadata:
  name: healthpoints
  namespace: default
  labels:
    app: healthpoints
spec:
  selector:
    app: healthpoints
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
